name: deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}