name: podlint

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
    
      - name: Install Cocoapods
        run: gem install cocoapods
      
      - name: Lib Lint
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
