name: test

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    
    runs-on: macos-14
    
    steps:
      - uses: swift-actions/setup-swift@v1
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v